### ISSUE TITLE
'ReaderManager.h' file not found

### ISSUE THREAD

**Issue by chetanbuddh** [flomio/flomio_cordova_plugin#19]
I follow every step from documentation.
But didn't run in ios.
It throws 

```
platforms/ios/Armill/Plugins/com.flomio.sdk/FlomioPlugin.h:7:9: 'ReaderManager.h' file not found
/*
FlomioPlugin.h
Uses Flomio SDK version 1.9
*/

#import <Cordova/CDV.h>
#import "ReaderManager.h"
```

it display `error in #import "ReaderManager.h" line`

I don't what is Flomio SDK version 1.9 in where it is available

**Comment by JohnMcLear** [comment]
I went through and tidied up your issue for you, please look at the markup I used and use it for further issues.

**Comment by JohnMcLear** [comment]
Do you have ReaderManager.h on your file system at all?

**Comment by chetanbuddh** [comment]
No, i haven't ReaderManger.h and i don't how to get it

**Comment by grundyoso** [comment]
ReaderManager.h is a file contained in the Flomio SDK that is a direct dependency of this Cordova Library. What that means is that after installing this Cordova plugin you have to manually drag/drop the Flomio SDK bundle into your iOS (or Android) build project in order to provide the services the plugin needs. (Note: we know this is not ideal and we are working at streamlining this process, but this is how it works now). 

Per README line: 

> Requires Flomio SDK version 1.9 [Get yours here.](http://flomio.com/shop/apps/flomio-sdk-basic-turnkey-oem-support/)

Also worth following is issue #7
